services:
  bejebeje-mvc:
    build:
      context: .
      dockerfile: ./Bejebeje.Mvc/Dockerfile
      labels:
        com.bejebeje.description: "Bejebeje MVC"
      secrets:
        - gh_pat
    ports:
      - "5010:5005"
    env_file:
      - ./variables.env
    depends_on:
      - database
      - seq
    networks:
      - bejebeje_network
    container_name: bejebeje-mvc

  database:
    image: postgres:18.3
    ports:
      - "8002:5432"
    volumes:
      - database-data:/var/lib/postgresql
    env_file:
      - ./variables.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bejebeje_network
    container_name: bejebeje-database

  seq:
    image: datalust/seq:2025.2
    ports:
      - "8003:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    volumes:
      - seq-data:/data
    networks:
      - bejebeje_network
    container_name: bejebeje-seq

volumes:
  database-data:
    name: bejebeje-database-data
  seq-data:
    name: bejebeje-seq-data

networks:
  bejebeje_network:
    driver: bridge

secrets:
  gh_pat:
    environment: GH_PACKAGES_TOKEN

