version: "3.7"

services:
  bejebeje-mvc:
    build:
      context: .
      dockerfile: ./Bejebeje.Mvc/Dockerfile
      labels:
        com.bejebeje.description: "Bejebeje MVC"
    image: bejebeje-mvc:latest
    ports:
      - "5010:5005"
    env_file:
      - ./variables.env
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - "8002:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    env_file:
      - ./variables.env

volumes:
  data-volume:
