services:
  bejebeje-mvc:
    build:
      context: .
      dockerfile: ./Bejebeje.Mvc/Dockerfile
      labels:
        com.bejebeje.description: "Bejebeje MVC"
    ports:
      - "5010:5005"
    env_file:
      - ./variables.env
    depends_on:
      - database
    networks:
      - bejebeje_network
    container_name: bejebeje-mvc

  database:
    image: postgres:17.2
    ports:
      - "8002:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    env_file:
      - ./variables.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bejebeje_network
    container_name: bejebeje-database

volumes:
  data-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/postgresql

networks:
  bejebeje_network:
    driver: bridge

