// <auto-generated />
using System;
using Bejebeje.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bejebeje.DataAccess.Migrations
{
    [DbContext(typeof(BbContext))]
    [Migration("20260324130247_AddBbPointsUserAndPointEventTables")]
    partial class AddBbPointsUserAndPointEventTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bejebeje.Shared.Domain.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("HasImage")
                        .HasColumnType("boolean")
                        .HasColumnName("has_image");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<char>("Sex")
                        .HasColumnType("character(1)")
                        .HasColumnName("sex");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.ArtistSlug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_artist_slugs");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_artist_slugs_artist_id");

                    b.ToTable("artist_slugs", (string)null);
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("HasImage")
                        .HasColumnType("boolean")
                        .HasColumnName("has_image");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<char>("Sex")
                        .HasColumnType("character(1)")
                        .HasColumnName("sex");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.AuthorSlug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_author_slugs");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_author_slugs_author_id");

                    b.ToTable("author_slugs", (string)null);
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.Lyric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lyrics");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_lyrics_artist_id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_lyrics_author_id");

                    b.ToTable("lyrics", (string)null);
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.LyricReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actioned_at");

                    b.Property<string>("ActionedBy")
                        .HasColumnType("text")
                        .HasColumnName("actioned_by");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LyricId")
                        .HasColumnType("integer")
                        .HasColumnName("lyric_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lyric_reports");

                    b.HasIndex("LyricId")
                        .HasDatabaseName("ix_lyric_reports_lyric_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_lyric_reports_user_id_created_at");

                    b.HasIndex("UserId", "LyricId", "Status")
                        .HasDatabaseName("ix_lyric_reports_user_id_lyric_id_status");

                    b.ToTable("lyric_reports", (string)null);
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.LyricSlug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("LyricId")
                        .HasColumnType("integer")
                        .HasColumnName("lyric_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_lyric_slugs");

                    b.HasIndex("LyricId")
                        .HasDatabaseName("ix_lyric_slugs_lyric_id");

                    b.ToTable("lyric_slugs", (string)null);
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.PointEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_point_events");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_point_events_user_id_created_at");

                    b.HasIndex("UserId", "ActionType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_point_events_user_id_action_type_entity_id");

                    b.ToTable("point_events", (string)null);
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistApprovalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("artist_approval_points");

                    b.Property<int>("ArtistSubmissionPoints")
                        .HasColumnType("integer")
                        .HasColumnName("artist_submission_points");

                    b.Property<string>("CognitoUserId")
                        .HasColumnType("text")
                        .HasColumnName("cognito_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LastSeenPoints")
                        .HasColumnType("integer")
                        .HasColumnName("last_seen_points");

                    b.Property<int>("LyricApprovalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("lyric_approval_points");

                    b.Property<int>("LyricSubmissionPoints")
                        .HasColumnType("integer")
                        .HasColumnName("lyric_submission_points");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("ReportAcknowledgementPoints")
                        .HasColumnType("integer")
                        .HasColumnName("report_acknowledgement_points");

                    b.Property<int>("ReportSubmissionPoints")
                        .HasColumnType("integer")
                        .HasColumnName("report_submission_points");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CognitoUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_cognito_user_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.ArtistSlug", b =>
                {
                    b.HasOne("Bejebeje.Shared.Domain.Artist", null)
                        .WithMany("Slugs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_slugs_artists_artist_id");
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.AuthorSlug", b =>
                {
                    b.HasOne("Bejebeje.Shared.Domain.Author", null)
                        .WithMany("Slugs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_author_slugs_authors_author_id");
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.Lyric", b =>
                {
                    b.HasOne("Bejebeje.Shared.Domain.Artist", "Artist")
                        .WithMany("Lyrics")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lyrics_artists_artist_id");

                    b.HasOne("Bejebeje.Shared.Domain.Author", "Author")
                        .WithMany("Lyrics")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk_lyrics_authors_author_id");

                    b.Navigation("Artist");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.LyricSlug", b =>
                {
                    b.HasOne("Bejebeje.Shared.Domain.Lyric", null)
                        .WithMany("Slugs")
                        .HasForeignKey("LyricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lyric_slugs_lyrics_lyric_id");
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.PointEvent", b =>
                {
                    b.HasOne("Bejebeje.Shared.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_point_events_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.Artist", b =>
                {
                    b.Navigation("Lyrics");

                    b.Navigation("Slugs");
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.Author", b =>
                {
                    b.Navigation("Lyrics");

                    b.Navigation("Slugs");
                });

            modelBuilder.Entity("Bejebeje.Shared.Domain.Lyric", b =>
                {
                    b.Navigation("Slugs");
                });
#pragma warning restore 612, 618
        }
    }
}
