// <auto-generated />
using System;
using Bejebeje.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bejebeje.DataAccess.Migrations
{
    [DbContext(typeof(BbContext))]
    partial class BbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Bejebeje.Domain.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name");

                    b.Property<int>("ImageId")
                        .HasColumnName("image_id");

                    b.Property<bool>("IsApproved")
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnName("modified_at");

                    b.Property<string>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("ImageId")
                        .HasName("ix_artists_image_id");

                    b.ToTable("artists");
                });

            modelBuilder.Entity("Bejebeje.Domain.ArtistSlug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("ArtistId")
                        .HasColumnName("artist_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_artist_slug");

                    b.HasIndex("ArtistId")
                        .HasName("ix_artist_slug_artist_id");

                    b.ToTable("artist_slug");
                });

            modelBuilder.Entity("Bejebeje.Domain.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .HasColumnName("data");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.ToTable("images");
                });

            modelBuilder.Entity("Bejebeje.Domain.Lyric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("ArtistId")
                        .HasColumnName("artist_id");

                    b.Property<string>("Body")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsApproved")
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnName("modified_at");

                    b.Property<string>("Title")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lyrics");

                    b.HasIndex("ArtistId")
                        .HasName("ix_lyrics_artist_id");

                    b.ToTable("lyrics");
                });

            modelBuilder.Entity("Bejebeje.Domain.LyricSlug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnName("is_primary");

                    b.Property<int>("LyricId")
                        .HasColumnName("lyric_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_lyric_slugs");

                    b.HasIndex("LyricId")
                        .HasName("ix_lyric_slugs_lyric_id");

                    b.ToTable("lyric_slugs");
                });

            modelBuilder.Entity("Bejebeje.Domain.Artist", b =>
                {
                    b.HasOne("Bejebeje.Domain.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .HasConstraintName("fk_artists_images_image_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bejebeje.Domain.ArtistSlug", b =>
                {
                    b.HasOne("Bejebeje.Domain.Artist")
                        .WithMany("Slugs")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("fk_artist_slug_artists_artist_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bejebeje.Domain.Lyric", b =>
                {
                    b.HasOne("Bejebeje.Domain.Artist")
                        .WithMany("Lyrics")
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("fk_lyrics_artists_artist_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bejebeje.Domain.LyricSlug", b =>
                {
                    b.HasOne("Bejebeje.Domain.Lyric")
                        .WithMany("Slugs")
                        .HasForeignKey("LyricId")
                        .HasConstraintName("fk_lyric_slugs_lyrics_lyric_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
